version: '3.8'

services:
  backend:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - uploads-data:/app/uploads

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  uploads-data: